name: Node
on: [push]
jobs:
  test:
    name: Node ${{ matrix.node-version }} . ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest] # failing on [windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: make clean
    - run: npm i
    - name: Setup emsdk (use cache if found, create otherwise)  
      uses: mymindstorm/setup-emsdk@v7
      with:
        version: 1.39.11
        actions-cache-folder: 'emsdk-cache-folder'
        no-cache: true
    - name: Compile WASM
      run: make wasm
    - run: npm test
